service: slack-alerts

provider:
  name: aws
  runtime: python3.6

functions:
  notify_slack:
    name: notify-slack
    handler: notify_slack.lambda_handler
    description: Alerting to Slack
    environment:
      SLACK_TOKEN: ${opt:token}
      SLACK_CHANNEL: ${opt:channel}

custom:
  pythonRequirements:
    dockerizePip: true

plugins:
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**
